### ISSUE TITLE
Bottom panel buttons not visible

### ISSUE THREAD

**Issue by nushen96** [daoodaba975/taaru#1]
I really like the Dark theme but the elements on the bottom panel (Problems, Output, Debug options, Console) are not visible until you hover the mouse over them.

**Comment by daoodaba975** [comment]
thanks @nushen96 to have noticed this issues
I will work on it in the next update soon.

**Comment by daoodaba975** [comment]
Hi @nushen96 I just fixed this issue, a new update will be available at the end of February.

**Comment by daoodaba975** [comment]
thanks for having this remark.
